[package]
authors = ["Mogwaicoin"]
edition = "2018"
name = "pallet-dotmog"
version = "2.0.0"
license = "Unlicense"
homepage = "https://www.mogwaicoin.org"
repository = "https://github.com/substrate-developer-hub/substrate-dmog/"
description = "FRAME pallet dmog for defining custom runtime logic."
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.4", default-features = false, features = ["derive"] }

frame-support = { version = "2.0.0", default-features = false, path = "../../../../frame/support" }
frame-system = { version = "2.0.0", default-features = false, path = "../../../../frame/system" }
sp-runtime = { version = "2.0.0", default-features = false, path = "../../../../primitives/runtime" }
sp-std = { version = "2.0.0", default-features = false, path = "../../../../primitives/std" }
rand_chacha = { default-features = false, version = '0.2.1' }

[dev-dependencies]
sp-core = { version = "2.0.0", default-features = false, path = "../../../../primitives/core" }
sp-io = { version = "2.0.0", path = "../../../../primitives/io" }

[features]
default = ['std']
std = [
    'codec/std',
    'frame-support/std',
    'frame-system/std',
    'sp-runtime/std',
    'sp-core/std',
    'rand_chacha/std',
]
